app:
  site:
    ui-base-url: https://mm.caseebak.com
    api-base-url: https://mm.caseebak.com

  mail:
    enabled: false
    sender-email: no-reply@caseebak.com
    support-email: no-reply@caseebak.com

  registration:
    enabled: true
    email-confirmation-enabled: false

  jwt:
    secret: "q2Y0W0rUQ7x0m0YcVb1s5H2N1G7S9nXk4FJx3q7lO0gY6W1mB8kP2aR5tU9zC4dE3fG6hJ1kL7pQ2sT5uV8w=="
