app:
  site:
    ui-base-url: https://mm.caseebak.com
    api-base-url: https://mm.caseebak.com

  mail:
    enabled: false
    sender-email: no-reply@caseebak.com
    support-email: no-reply@caseebak.com

  registration:
    enabled: true
    email-confirmation-enabled: false

  jwt:
    secret: "lYy6y2K8wZ6GmX2uWQe3s9nH8rB4VjP5fC7dT1qL0kR9uM2aXxY8Zp3bN6hJ4sFvQ1eR2tW5yU7iO0cD8E9g=="
