services:
  wisemapping:
    image: wisemapping/wisemapping:latest
    restart: unless-stopped
    environment:
      APP_SITE_UI_BASE_URL: https://wm.caseebak.com
      APP_SITE_API_BASE_URL: https://wm.caseebak.com
      APP_MAIL_ENABLED: "false"
      APP_REGISTRATION_ENABLED: "true"
      APP_REGISTRATION_EMAIL_CONFIRMATION_ENABLED: "false"
      APP_JWT_SECRET: "q2Y0W0rUQ7x0m0YcVb1s5H2N1G7S9nXk4FJx3q7lO0gY6W1mB8kP2aR5tU9zC4dE3fG6hJ1kL7pQ2sT5uV8w=="
    labels:
      - traefik.enable=true
      - traefik.http.routers.wm.rule=Host(`wm.caseebak.com`)
      - traefik.http.routers.wm.entrypoints=https
      - traefik.http.routers.wm.tls=true
      - traefik.http.routers.wm.tls.certresolver=letsencrypt
      - traefik.http.services.wm.loadbalancer.server.port=80
