services:
  wisemapping:
    image: wisemapping/wisemapping:latest
    restart: unless-stopped
    environment:
      APP_SITE_UI_BASE_URL: https://mm.caseebak.com
      APP_SITE_API_BASE_URL: https://mm.caseebak.com
      APP_MAIL_ENABLED: "false"
      APP_REGISTRATION_ENABLED: "true"
      APP_REGISTRATION_EMAIL_CONFIRMATION_ENABLED: "false"
      APP_JWT_SECRET: "lYy6y2K8wZ6GmX2uWQe3s9nH8rB4VjP5fC7dT1qL0kR9uM2aXxY8Zp3bN6hJ4sFvQ1eR2tW5yU7iO0cD8E9g=="
      SPRING_DATASOURCE_URL: jdbc:hsqldb:file:/data/db/wisemapping
    command: >
      sh -c "mkdir -p /data/db && exec java -jar /app/wisemapping-api.jar"
    volumes:
      - wisemapping_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.wm.rule=Host(`mm.caseebak.com`)
      - traefik.http.routers.wm.entrypoints=https
      - traefik.http.routers.wm.tls=true
      - traefik.http.routers.wm.tls.certresolver=letsencrypt
      - traefik.http.services.wm.loadbalancer.server.port=8080

volumes:
  wisemapping_data:
